from TTS.api import TTS
import os

# Modeli seç
model_name = "tts_models/multilingual/multi-dataset/your_tts"
tts = TTS(model_name)

# Konuşmacı listesini al ve temizle
speakers = [s.strip() for s in tts.speakers]
print("Speakers:", speakers)

# Kullanmak istediğin konuşmacı ve dil
speaker_id = "female-en-5"
language = "en"

# Çıkış klasörü
output_dir = "spoof_audio"
os.makedirs(output_dir, exist_ok=True)

# Cümleler
sentences = [
    "This is a fake voice generated by TTS.",
    "We are creating spoof audio samples.",
    "Voice spoofing can be dangerous."
]

# Ses üret
for i, sentence in enumerate(sentences):
    file_path = os.path.join(output_dir, f"spoof_{i}.wav")
    tts.tts_to_file(text=sentence, file_path=file_path, speaker=speaker_id, language=language)
    print(f"Saved: {file_path}")
